### ISSUE TITLE
[RFC] Release Binaries via GitHub Releases

### ISSUE THREAD

**Issue by kenju** [cloudflare/ebpf_exporter#79]
# Background

Publishing cross-platform binaries might be great. Users can simply download anything they want (via cURL, wget, etc.) and can use them. The release operation can be easily integrated into CI pipeline, so it would not be a burden for you once you have set it up.

# Example

[Github Releases](https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository) might be a good option. ~You can achieve this by using any tool, but I personally recommend https://github.com/goreleaser/goreleaser/ because it is easy to setup.~ I have just realized that [goreleaser does not support cgo](https://goreleaser.com/limitations/cgo/), which I guess it does not work because iovisor/gobpf/bcc is dependent on cgo.

The release page of statsd_exporter is worth for looking at:

- https://github.com/prometheus/statsd_exporter/releases

<img width="784" alt="Screen Shot 2020-05-30 at 16 07 42" src="https://user-images.githubusercontent.com/4186381/83322075-c6598500-a28f-11ea-84db-f707790f5b38.png">

# NOTE

@bobrik What do you think? Also, I'm happy to work it on :)

**Comment by bobrik** [comment]
eBPF is only supported on linux. Plus, you need libbcc packages for the target architecture to both build and run ebpf_exporter. BCC itself only provides amd64 variant ([mislabeled as `all`, it seems](https://repo.iovisor.org/apt/bionic/pool/main/b/bcc/)), and we don't even use that, since the latest published version is quite old.

Our production builds have some patches to build on aarch64, and I don't know if anyone is really using ebpf_exporter outside of x86_64.

I think bcc builds needs to be fixed before we get to publishing cross-platform binaries.

See also: #32.

**Comment by kenju** [comment]
Thank you for looking at to it.

Sorry, I implicitly put two discussion point into this issue 🙏 Let me clarify...

1. Could you release minimum binary build using GitHub Releases, Bintray, etc...
    - Just distributing a binary with `GOOS=linux GOARCH=amd64` is fine. Then we can just download the binary with cURL or wget and use it without building it on linux/x86_64
2. Shall we discuss about distributing **cross-platform** binaries
    - Yes I understand that this is out of the point [as you have described in this comment](https://github.com/cloudflare/ebpf_exporter/issues/79#issuecomment-636405213)

---

Let me forget about the cross-platform things. So, let me ask you again about the first discussion point, which is a possibility for distributing a built golang binary? I guess few lines of bash script will be fine.
