### ISSUE TITLE
Support for uprobes

### ISSUE THREAD

**Issue by hsane2001** [cloudflare/ebpf_exporter#91]
Cant seem to get any data from bpf programs using uprobes, seems there is only support for kprobes. I dont see any examples either. Is that true or am I missing something?

**Comment by bobrik** [comment]
That's right. The problem with uprobes when compared to bcc-tools is that over time binaries change and you need to wire up `ebpf_exporter` to deal with it somehow. Adding support for uprobes is trivial otherwise.

**Comment by hsane2001** [comment]
Thanks bobrik, Anyway I can add support for uprobes?, I see the the functions to attach the uprobe are present in the "~/go/src/github.com/cloudflare/ebpf_exporter/vendor/github.com/iovisor/gobpf/bcc/module.go" but the support is absent in the config file.
How do You suggest I gather data from my bcc program using uprobes through ebpf_exporter?

**Comment by bobrik** [comment]
You can't use existing version of `ebpf_exporter` with uprobes, code changes are required to add support.

**Comment by rob-scheepens** [comment]
@bobrik , since you mentioned adding support is trivial, I tried to add some code for uprobes, obviously being overly simplistic as I am not a developer. ;) I basically took the mentions of krpobe in config.go, attach.go and exporter.go and copied them, changing kprobe to uprobe. That resulted in the following build error:
```
# github.com/cloudflare/ebpf_exporter/exporter
../../exporter/attach.go:110:79: cannot use module.AttachUprobe (type func(string, string, int, int) error) as type probeAttacherWithMaxActive in argument to withMaxActive
../../exporter/attach.go:115:79: cannot use module.AttachUretprobe (type func(string, string, int, int) error) as type probeAttacherWithMaxActive in argument to withMaxActive
```
The point is: I'd rather rewrite some of the scripts/programs that use uprobes every now and then, if that's the tradeoff against having no uprobe support at all. Adding uprobe support would be a huge win imo. I'm happy to try more, but as said, I'm not a dev and I'm unsure where to go from here.

**Comment by bobrik** [comment]
See #150 for an example of a `uprobe`.
